name: Translate Readme

on:
    push:
        branches: ['**']

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 3

            - name: Auto Translate
              uses: Lin-jun-xiang/action-translate-readme@v2
              with:
                token: ${{ secrets.Action_Bot }}
                zhipuai: ${{ secrets.zhipuai_api_key }} # Optional: Based on step3
                openai: ${{ secrets.openai_api_key }}  # Optional: Based on step3
                langs: "en,French" # You can define any langs
